# Generated by Django 4.2.13 on 2024-06-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expression",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="additions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="diagrams",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="illustration_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="marginal_annotations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="seal_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manuscriptpart",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="person",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionexpression",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionmanuscript",
            name="additions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionmanuscript",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionmanuscript",
            name="diagrams",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionmanuscript",
            name="illustration_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionmanuscript",
            name="marginal_annotations",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionmanuscript",
            name="seal_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionmanuscriptpart",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionperson",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionwork",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="expression",
            name="language",
            field=models.ManyToManyField(
                blank=True, null=True, to="apis_ontology.language"
            ),
        ),
        migrations.AlterField(
            model_name="expression",
            name="locus",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="expression",
            name="script_body",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="expression",
            name="script_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="expression",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="condition",
            field=models.ManyToManyField(
                blank=True, null=True, to="apis_ontology.manuscriptcondition"
            ),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="extent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="foliation_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="identifier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="leaf_dimension",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="written_dimension",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="manuscriptpart",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="person",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="fathers_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="grandfathers_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="laqab_kunya",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="name_in_arabic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="profession",
            field=models.ManyToManyField(
                blank=True, null=True, to="apis_ontology.profession"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="title",
            field=models.ManyToManyField(
                blank=True, null=True, to="apis_ontology.title"
            ),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="locus",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="script_body",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="script_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="versionmanuscript",
            name="extent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="versionmanuscript",
            name="foliation_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="versionmanuscript",
            name="identifier",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="versionmanuscript",
            name="leaf_dimension",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="versionmanuscript",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="versionmanuscript",
            name="written_dimension",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="versionmanuscriptpart",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="fathers_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="grandfathers_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="laqab_kunya",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="name_in_arabic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
