# Generated by Django 4.2.13 on 2024-06-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0002_expression_description_manuscript_additions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="title",
            name="abbreviation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
