# Generated by Django 4.2.13 on 2024-07-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0003_alter_title_abbreviation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profession",
            options={
                "verbose_name": "profession",
                "verbose_name_plural": "professions",
            },
        ),
        migrations.AlterModelOptions(
            name="title",
            options={"verbose_name": "title", "verbose_name_plural": "titles"},
        ),
        migrations.AddField(
            model_name="event",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="expression",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manuscriptpart",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionevent",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionexpression",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versioninstitution",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionmanuscript",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionmanuscriptpart",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionplace",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="versionwork",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="alternative_names",
            field=models.TextField(blank=True, null=True),
        ),
    ]
