# Generated by Django 4.2.13 on 2024-07-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0004_alter_profession_options_alter_title_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="name_in_arabic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="expression",
            name="name_in_arabic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="institution",
            name="name_in_arabic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="manuscript",
            name="name_in_arabic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="manuscriptpart",
            name="name_in_arabic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="place",
            name="name_in_arabic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="versionevent",
            name="name_in_arabic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="versionexpression",
            name="name_in_arabic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="versioninstitution",
            name="name_in_arabic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="versionmanuscript",
            name="name_in_arabic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="versionmanuscriptpart",
            name="name_in_arabic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="versionplace",
            name="name_in_arabic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="versionwork",
            name="name_in_arabic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="work",
            name="name_in_arabic",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="expression",
            name="language",
            field=models.ManyToManyField(blank=True, to="apis_ontology.language"),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="condition",
            field=models.ManyToManyField(
                blank=True, to="apis_ontology.manuscriptcondition"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="profession",
            field=models.ManyToManyField(blank=True, to="apis_ontology.profession"),
        ),
        migrations.AlterField(
            model_name="person",
            name="title",
            field=models.ManyToManyField(blank=True, to="apis_ontology.title"),
        ),
    ]
