# Generated by Django 4.2.15 on 2024-08-21 13:07

import apis_core.generic.abc
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0005_event_name_in_arabic_expression_name_in_arabic_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ScriptType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "script type",
                "verbose_name_plural": "Script type",
            },
            bases=(models.Model,),
        ),
        migrations.AlterModelOptions(
            name="expression",
            options={
                "verbose_name": "expression",
                "verbose_name_plural": "expressions",
            },
        ),
        migrations.RenameField(
            model_name="manuscriptcondition",
            old_name="label",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="manuscriptparttype",
            old_name="label",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="expression",
            name="script_body",
        ),
        migrations.RemoveField(
            model_name="expression",
            name="script_title",
        ),
        migrations.RemoveField(
            model_name="versionexpression",
            name="script_body",
        ),
        migrations.RemoveField(
            model_name="versionexpression",
            name="script_title",
        ),
        migrations.AddField(
            model_name="expression",
            name="script_type_body",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="script_type_body",
                to="apis_ontology.scripttype",
            ),
        ),
        migrations.AddField(
            model_name="expression",
            name="script_type_title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="script_type_title",
                to="apis_ontology.scripttype",
            ),
        ),
        migrations.AddField(
            model_name="versionexpression",
            name="script_type_body",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apis_ontology.scripttype",
            ),
        ),
        migrations.AddField(
            model_name="versionexpression",
            name="script_type_title",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="apis_ontology.scripttype",
            ),
        ),
    ]
