# Generated by Django 4.2.16 on 2024-09-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0007_event_pk_old_expression_pk_old_institution_pk_old_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="versionevent",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical event",
                "verbose_name_plural": "historical Events",
            },
        ),
        migrations.AlterModelOptions(
            name="versionexpression",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical expression",
                "verbose_name_plural": "historical expressions",
            },
        ),
        migrations.AlterModelOptions(
            name="versioninstitution",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical institution",
                "verbose_name_plural": "historical Institutions",
            },
        ),
        migrations.AlterModelOptions(
            name="versionmanuscript",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical manuscript",
                "verbose_name_plural": "historical Manuscripts",
            },
        ),
        migrations.AlterModelOptions(
            name="versionmanuscriptpart",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical manuscript part",
                "verbose_name_plural": "historical Manuscript parts",
            },
        ),
        migrations.AlterModelOptions(
            name="versionperson",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical person",
                "verbose_name_plural": "historical Persons",
            },
        ),
        migrations.AlterModelOptions(
            name="versionplace",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical place",
                "verbose_name_plural": "historical Places",
            },
        ),
        migrations.AlterModelOptions(
            name="versionwork",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical work",
                "verbose_name_plural": "historical Works",
            },
        ),
        migrations.RenameField(
            model_name="manuscript",
            old_name="foliation_type",
            new_name="foliation_note",
        ),
        migrations.RenameField(
            model_name="versionmanuscript",
            old_name="foliation_type",
            new_name="foliation_note",
        ),
        migrations.AlterField(
            model_name="event",
            name="pk_old",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="expression",
            name="pk_old",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="institution",
            name="pk_old",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="pk_old",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="manuscriptpart",
            name="pk_old",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="forename",
            field=models.CharField(blank=True, default="", max_length=4096),
        ),
        migrations.AlterField(
            model_name="person",
            name="pk_old",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="surname",
            field=models.CharField(blank=True, default="", max_length=4096),
        ),
        migrations.AlterField(
            model_name="place",
            name="label",
            field=models.CharField(blank=True, default="", max_length=4096),
        ),
        migrations.AlterField(
            model_name="place",
            name="pk_old",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="versionevent",
            name="pk_old",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="versionexpression",
            name="pk_old",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="versioninstitution",
            name="pk_old",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="versionmanuscript",
            name="pk_old",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="versionmanuscriptpart",
            name="pk_old",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="forename",
            field=models.CharField(blank=True, default="", max_length=4096),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="pk_old",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="surname",
            field=models.CharField(blank=True, default="", max_length=4096),
        ),
        migrations.AlterField(
            model_name="versionplace",
            name="label",
            field=models.CharField(blank=True, default="", max_length=4096),
        ),
        migrations.AlterField(
            model_name="versionplace",
            name="pk_old",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="versionwork",
            name="pk_old",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="work",
            name="pk_old",
            field=models.BigIntegerField(blank=True, editable=False, null=True),
        ),
    ]
