# Generated by Django 4.2.16 on 2024-09-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0008_alter_versionevent_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manuscript",
            name="foliation_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="versionmanuscript",
            name="foliation_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
