# Generated by Django 4.2.16 on 2024-10-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0012_remove_acopyof_certainty_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="acopyof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="ancestralcountryof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="annotatedby",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="attributedto",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="authoredby",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="authorof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="authorofcontent",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="biographerof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="bornin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="boughtin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="brotherof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="buriedin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="captorof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="certificatefor",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="classificationof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="colleagueof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="commanderof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="commentaryof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="commentatorof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="commentedtheworkof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="commissionerof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="connectedto",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="contains",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="containscopyof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="copiedby",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="copiedin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="copyistof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="cousinof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="dedicateeof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="descendantof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="describedby",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="diedin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="editedby",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="eulogized",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="executedin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="exiledfrom",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="explanationof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="followerof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="founderof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="grandfatherof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="grandnephewof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="greatgrandfatherof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="heldin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="imprisonedin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="inthelibraryof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="judgein",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="killedin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="livedin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="locatedat",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="locatedin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="madepilgrimageto",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="mentionedin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="metwith",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="murdererof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="nephewof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="ownedby",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="ownerof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="participatedintheconquestof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="participatedinthefoundingof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="partof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="patronof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="placementionedin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="placeofacquisition",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="placeofbirth",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="placeofcompositionof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="placeofcopyof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="purchaserof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="rivalof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="ruledover",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="rulerof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="sonof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="spouseof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="studiedat",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="studiedin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="studiedwith",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="subjectofwork",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="successorof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="summaryof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="supplementto",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="taughtin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="teacherat",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="teacherof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="testrel",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="translationof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="usedin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionacopyof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionancestralcountryof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionannotatedby",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionattributedto",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionauthoredby",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionauthorof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionauthorofcontent",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionbiographerof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionbornin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionboughtin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionbrotherof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionburiedin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versioncaptorof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versioncertificatefor",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionclassificationof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versioncolleagueof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versioncommanderof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versioncommentaryof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versioncommentatorof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versioncommentedtheworkof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versioncommissionerof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionconnectedto",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versioncontains",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versioncontainscopyof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versioncopiedby",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versioncopiedin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versioncopyistof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versioncousinof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versiondedicateeof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versiondescendantof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versiondescribedby",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versiondiedin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versioneditedby",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versioneulogized",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionexecutedin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionexiledfrom",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionexplanationof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionfollowerof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionfounderof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versiongrandfatherof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versiongrandnephewof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versiongreatgrandfatherof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionheldin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionimprisonedin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versioninthelibraryof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionjudgein",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionkilledin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionlivedin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionlocatedat",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionlocatedin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionmadepilgrimageto",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionmentionedin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionmetwith",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionmurdererof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionnephewof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionownedby",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionownerof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionparticipatedintheconquestof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionparticipatedinthefoundingof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionpartof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionpatronof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionplacementionedin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionplaceofacquisition",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionplaceofbirth",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionplaceofcompositionof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionplaceofcopyof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionpurchaserof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionrivalof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionruledover",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionrulerof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionsonof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionspouseof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionstudiedat",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionstudiedin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionstudiedwith",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionsubjectofwork",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionsuccessorof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionsummaryof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionsupplementto",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versiontaughtin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionteacherat",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionteacherof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versiontestrel",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versiontranslationof",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionusedin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionvisited",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionworkedat",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionworkedfor",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="versionworkin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="visited",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="workedat",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="workedfor",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="workin",
            name="certainty",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("medium", "medium"),
                    ("high", "high"),
                    ("unknown", "unknown"),
                ],
                default="unknown",
                max_length=7,
            ),
        ),
    ]
