# Generated by Django 5.1.5 on 2025-01-22 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0017_alter_event_status_alter_expression_status_and_more"),
        ("apis_ontology", "0017_remove_acopyof_end_date_and_more"),
    ]

    operations = []
