# Generated by Django 5.1.8 on 2025-04-14 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0021_remove_versionevent_self_contenttype_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acopyof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="ancestralcountryof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="annotatedby",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="attributedto",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="authoredby",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="authorof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="authorofcontent",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="biographerof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="bornin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="boughtin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="brotherof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="buriedin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="captorof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="certificatefor",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="classificationof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="colleagueof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="commanderof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="commentaryof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="commentatorof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="commentedtheworkof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="commissionerof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="connectedto",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="contains",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="containscopyof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="copiedby",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="copiedin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="copyistof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="cousinof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="dedicateeof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="descendantof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="describedby",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="diedin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="editedby",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="eulogized",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="event",
            options={
                "ordering": ["pk"],
                "verbose_name": "event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.AlterModelOptions(
            name="executedin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="exiledfrom",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="explanationof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="expression",
            options={
                "ordering": ["pk"],
                "verbose_name": "expression",
                "verbose_name_plural": "expressions",
            },
        ),
        migrations.AlterModelOptions(
            name="followerof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="founderof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="grandfatherof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="grandnephewof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="greatgrandfatherof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="heldin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="imprisonedin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="institution",
            options={
                "ordering": ["pk"],
                "verbose_name": "institution",
                "verbose_name_plural": "Institutions",
            },
        ),
        migrations.AlterModelOptions(
            name="inthelibraryof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="judgein",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="killedin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="livedin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="locatedat",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="locatedin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="madepilgrimageto",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="manuscript",
            options={
                "ordering": ["pk"],
                "verbose_name": "manuscript",
                "verbose_name_plural": "Manuscripts",
            },
        ),
        migrations.AlterModelOptions(
            name="manuscriptpart",
            options={
                "ordering": ["pk"],
                "verbose_name": "manuscript part",
                "verbose_name_plural": "Manuscript parts",
            },
        ),
        migrations.AlterModelOptions(
            name="mentionedin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="metwith",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="murdererof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="nephewof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="ownedby",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="ownerof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="participatedintheconquestof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="participatedinthefoundingof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="partof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="patronof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["pk"],
                "verbose_name": "person",
                "verbose_name_plural": "Persons",
            },
        ),
        migrations.AlterModelOptions(
            name="place",
            options={
                "ordering": ["pk"],
                "verbose_name": "place",
                "verbose_name_plural": "Places",
            },
        ),
        migrations.AlterModelOptions(
            name="placementionedin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="placeofacquisition",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="placeofannotationof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="placeofbirth",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="placeofcompositionof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="placeofcopyof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="purchaserof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="refutationof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="rivalof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="ruledover",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="rulerof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="sonof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="spouseof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="studiedat",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="studiedin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="studiedwith",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="subjectofwork",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="successorof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="summaryof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="supplementto",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="taughtin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="teacherat",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="teacherof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="testrel",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="translationof",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="usedin",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="visited",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="work",
            options={
                "ordering": ["pk"],
                "verbose_name": "work",
                "verbose_name_plural": "Works",
            },
        ),
        migrations.AlterModelOptions(
            name="workedat",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="workedfor",
            options={"ordering": ["pk"]},
        ),
        migrations.AlterModelOptions(
            name="workin",
            options={"ordering": ["pk"]},
        ),
    ]
