# Generated by Django 5.1.9 on 2025-06-18 09:44

import apis_core.generic.abc
import django.db.models.deletion
import django_interval.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0022_alter_acopyof_options_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("relations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainsManuscriptPart",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                (
                    "end_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "end",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=7,
                    ),
                ),
                (
                    "pk_old",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
            bases=(
                "relations.relation",
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="CopiedInPlace",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                (
                    "end_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "end",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=7,
                    ),
                ),
                (
                    "pk_old",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
            bases=(
                "relations.relation",
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="InstitutionLocatedIn",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                (
                    "end_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "end",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=7,
                    ),
                ),
                (
                    "pk_old",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
            bases=(
                "relations.relation",
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="InstitutionOfCompositionOf",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                (
                    "end_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "end",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=7,
                    ),
                ),
                (
                    "pk_old",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
            bases=(
                "relations.relation",
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="MentionedInWork",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                (
                    "end_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "end",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=7,
                    ),
                ),
                (
                    "pk_old",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
            bases=(
                "relations.relation",
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="VersionContainsManuscriptPart",
            fields=[
                (
                    "relation_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="relations.relation",
                    ),
                ),
                (
                    "end_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("subj_object_id", models.PositiveIntegerField()),
                ("obj_object_id", models.PositiveIntegerField()),
                (
                    "version_tag",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "start",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "end",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=7,
                    ),
                ),
                (
                    "pk_old",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "obj_content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "subj_content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical contains manuscript part",
                "verbose_name_plural": "historical contains manuscript parts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(
                simple_history.models.HistoricalChanges,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="VersionCopiedInPlace",
            fields=[
                (
                    "relation_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="relations.relation",
                    ),
                ),
                (
                    "end_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("subj_object_id", models.PositiveIntegerField()),
                ("obj_object_id", models.PositiveIntegerField()),
                (
                    "version_tag",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "start",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "end",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=7,
                    ),
                ),
                (
                    "pk_old",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "obj_content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "subj_content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical copied in place",
                "verbose_name_plural": "historical copied in places",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(
                simple_history.models.HistoricalChanges,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="VersionInstitutionLocatedIn",
            fields=[
                (
                    "relation_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="relations.relation",
                    ),
                ),
                (
                    "end_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("subj_object_id", models.PositiveIntegerField()),
                ("obj_object_id", models.PositiveIntegerField()),
                (
                    "version_tag",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "start",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "end",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=7,
                    ),
                ),
                (
                    "pk_old",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "obj_content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "subj_content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical institution located in",
                "verbose_name_plural": "historical institution located ins",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(
                simple_history.models.HistoricalChanges,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="VersionInstitutionOfCompositionOf",
            fields=[
                (
                    "relation_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="relations.relation",
                    ),
                ),
                (
                    "end_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("subj_object_id", models.PositiveIntegerField()),
                ("obj_object_id", models.PositiveIntegerField()),
                (
                    "version_tag",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "start",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "end",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=7,
                    ),
                ),
                (
                    "pk_old",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "obj_content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "subj_content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical institution of composition of",
                "verbose_name_plural": "historical institution of composition ofs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(
                simple_history.models.HistoricalChanges,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="VersionMentionedInWork",
            fields=[
                (
                    "relation_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="relations.relation",
                    ),
                ),
                (
                    "end_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("subj_object_id", models.PositiveIntegerField()),
                ("obj_object_id", models.PositiveIntegerField()),
                (
                    "version_tag",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "start",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "end",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=7,
                    ),
                ),
                (
                    "pk_old",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "obj_content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "subj_content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical mentioned in work",
                "verbose_name_plural": "historical mentioned in works",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(
                simple_history.models.HistoricalChanges,
                models.Model,
            ),
        ),
    ]
