# Generated by Django 5.2.6 on 2025-12-11 07:29

import django.db.models.deletion
import django_interval.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0024_remove_versionacopyof_version_tag_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("relations", "0003_relation_relations_r_subj_content_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManuscriptPartHappenedInPlace",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                (
                    "end_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "end",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=7,
                    ),
                ),
                (
                    "pk_old",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
            bases=("relations.relation", models.Model),
        ),
        migrations.CreateModel(
            name="ManuscriptPartReadInPlace",
            fields=[
                (
                    "relation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="relations.relation",
                    ),
                ),
                (
                    "end_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "end",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=7,
                    ),
                ),
                (
                    "pk_old",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
            ],
            options={
                "ordering": ["pk"],
                "abstract": False,
            },
            bases=("relations.relation", models.Model),
        ),
        migrations.CreateModel(
            name="VersionManuscriptPartHappenedInPlace",
            fields=[
                (
                    "relation_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="relations.relation",
                    ),
                ),
                (
                    "end_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("subj_object_id", models.PositiveIntegerField(null=True)),
                ("obj_object_id", models.PositiveIntegerField(null=True)),
                (
                    "start",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "end",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=7,
                    ),
                ),
                (
                    "pk_old",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "obj_content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "subj_content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical manuscript part happened in place",
                "verbose_name_plural": "historical manuscript part happened in places",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="VersionManuscriptPartReadInPlace",
            fields=[
                (
                    "relation_ptr",
                    models.ForeignKey(
                        auto_created=True,
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        parent_link=True,
                        related_name="+",
                        to="relations.relation",
                    ),
                ),
                (
                    "end_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "end_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_to",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_from",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "start_date_sort",
                    models.DateField(
                        auto_created=True, blank=True, editable=False, null=True
                    ),
                ),
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("subj_object_id", models.PositiveIntegerField(null=True)),
                ("obj_object_id", models.PositiveIntegerField(null=True)),
                (
                    "start",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "end",
                    django_interval.fields.FuzzyDateParserField(blank=True, null=True),
                ),
                (
                    "certainty",
                    models.CharField(
                        choices=[
                            ("low", "low"),
                            ("medium", "medium"),
                            ("high", "high"),
                            ("unknown", "unknown"),
                        ],
                        default="unknown",
                        max_length=7,
                    ),
                ),
                (
                    "pk_old",
                    models.BigIntegerField(blank=True, editable=False, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "obj_content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "subj_content_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical manuscript part read in place",
                "verbose_name_plural": "historical manuscript part read in places",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
