# Generated by Django 5.2.6 on 2026-06-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis_ontology", "0026_event_hidden_import_log_expression_hidden_import_log_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GraphSearchSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(default="global", max_length=64, unique=True)),
                ("nodes", models.JSONField(blank=True, default=list)),
                ("links", models.JSONField(blank=True, default=list)),
                ("node_count", models.PositiveIntegerField(default=0, editable=False)),
                ("link_count", models.PositiveIntegerField(default=0, editable=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "graph search snapshot",
                "verbose_name_plural": "Graph search snapshots",
            },
        ),
    ]
